tab_spaces = 2
max_width = 80
use_field_init_shorthand = true
edition = "2018"
reorder_modules = true
brace_style = "AlwaysNextLine"
fn_args_layout = "Vertical"
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
space_before_colon = true
fn_single_line = false
empty_item_single_line = true
